site_name: Rudra Prasad Sahu
site_url: https://rudraprsd.github.io/
theme:
  name: material
  palette: 
    primary: brown
    accent: amber
    scheme: slate
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - tags
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - About: 
    - About Me: about/about.md
    - My Childhood: about/childhood.md
  - Tags: tags.md
  - Codes: 
    - Python: coding/hello_world.md
  - Blogs:
    - blog/index.md

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:rudraprasad01@outlook.com
    - icon: fontawesome/brands/github
      link: https://github.com/rudraprsd
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rudra-prasad-sahu/

copyright: Copyright &copy; 2025 Rudra Prasad Sahu